version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /static/rust
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /static/python
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /static/typescript
    schedule:
      interval: daily
