name: Push

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.BOT_SSH_KEY }}

      - name: Install dependencies
        run: poetry install

      - name: Run typecheck
        run: poetry run mypy .

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Install Node toolchain
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Push new versions
        run: |
          shopt -s extglob

          git config --global user.email "github@reservoirdb.com"
          git config --global user.name "ReservoirDB Bot"

          langs=(rust python typescript)

          gittempdir=$(mktemp -d)

          for lang in ${langs[@]}
          do
            git clone git@github.com:reservoirdb/reservoirdb-protocol-$lang.git $gittempdir/$lang
          done

          poetry run python -m linguafranca reservoirdb_protocol ${langs[@]}

          for lang in ${langs[@]}
          do
            rm -rf $gittempdir/$lang/!(.git)
            cp -a out/$lang/. $gittempdir/$lang

            pushd $gittempdir/$lang
            git status
            git add --all
            git diff-index --quiet HEAD || git commit \
              -m "Deploy: ${{ github.event.head_commit.message }}"\
              -m "Source: reservoirdb/linguafranca@${{ github.sha }}"\
              -m "Co-authored-by: ${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>"
            git push
            popd
          done
